apiVersion: 1

datasources:
  # Cassandra via REST API (Infinity plugin)
  - name: Cassandra-API
    type: yesoreyeram-infinity-datasource
    access: proxy
    uid: cassandra-api
    url: http://cassandra-api:3002
    isDefault: true
    jsonData:
      tlsSkipVerify: true
    editable: true
